### ISSUE TITLE
images

### ISSUE THREAD

**Issue by berak** [twhite2219/selfdrivingcarV1#1]
https://github.com/twhite2219/selfdrivingcarV1/blob/master/train_data/0/i%20%2837%29.jpg

is this really a"go left" situation ? no idea, what you're doing with your car later, but assuming, there's a single camera pointing forward, maybe use images from that perspective ? 

probably, restricting it to 3 cases like:

      |   |
      |   |            (forward)

         _____
       /     ___ 
      /    /
     |     |             (right)

       ____
     ____    \
          \     |          (left)
           |     |

will give much better results. (bare with my poor ascii graphics ;)

**Comment by twhite2219** [comment]
HI- yes I did consider that however it has to stay in between the lines, and the entire curve being recognised would mean it would try to follow it as one which is complicated with such crap motors, you have to assume the vehicle goes in a straight line unless the line ahead of it is past a 45 degree angle left or right in which case it would correct itself. I cannot figure out why none of the NN VALUES are correct and why it gives a score of 0... could it be the modloc?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by twhite2219** [comment]
See attached, car will go straight and alter course accordingly in real time to stay between two lines... [Image]

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by berak** [comment]
what's `modloc` ?

(and no i do not want outlook for ios ;)

**Comment by twhite2219** [comment]
Modloc Is the part that calculates the highest recieved probablilty from the NN and its location (0,1 or 2) or so i believe.


I think the NN has no reason as to why it doesnt work apart from something related to my setters... the number of iterations/backprop ratio maybe/ layer sizes ... maybe one of those is incorrect?


other than that the only thing I feel it could be is this :

  for(int i=0; i<train_classes.rows; i++)
  {
  train_classes.at<float>(i, train_labels.at<int>(i)) = 1.f;
  }
    cerr << train_data.size() << " " << train_classes.size() << endl;

    ann->train(train_data, ml::ROW_SAMPLE, train_classes);

 purely because i do not understand it.

One of the 4 mentioned issues must be the reason it is not working.... do you agree? if so how should it be?

________________________________

**Comment by twhite2219** [comment]
Apologies, I mean MinMaxLoc, and apologies regarding outlook for IOS :)


________________________________

**Comment by berak** [comment]
ah, ok. (and i'm just pulling your leg, no worries..)

**Comment by twhite2219** [comment]
see earlier message, think you missed it


________________________________

**Comment by berak** [comment]
> Modloc Is the part that calculates the highest recieved probablilty from the NN and its location (0,1 or 2) or so i believe. 

yes, each output node returns the probability of the resp. label

> I think the NN has no reason as to why it doesnt work apart from something related to my setters... the number of iterations/backprop ratio maybe/ layer sizes ... maybe one of those is incorrect? 

yes, please try ! (though "incorrect" might be the wrong word, "bad fit for your situation" 
also try with more hidden nodes, or more / less layers

>  purely because i do not understand it.

do you know, how an nn works ? to train it, you have to show it an input (100 pixels), and the expected output (3 nodes with probs [0..1]) the expected output for "1" would be (0,1,0)

let me check again, if you're somewhere inconsitent with your labels (the comments are all misleading)
0: left
1: right
2: straight

right ?

**Comment by twhite2219** [comment]
I re arranged last night to prioritise the training of directions before going straight so 0=left, 1=right and 2 now forward. I do understand the workings of the NN and MLP in general however I struggled to understand this line of the code within the training algorithm (and wether it was totally neccecary):  train_classes.at<float>(i, train_labels.at<int>(i)) = 1.f; 
and because I do not understand it I cannot rule it out as an error. 

OK , Will try changing layer sizes etc and see how that affects it, do you think changing iterations/backprop rate would also help/ what is normal values for both.

**Comment by berak** [comment]
> train_classes.at(i, train_labels.at(i)) = 1.f;

yes, totally nessecary. the responses are initially all 0 (Mat::zeros), if train_labels(i) is 2, this will make the response: (0,0,1)

also, maybe use [0..1] range for data [here](https://github.com/twhite2219/selfdrivingcarV1/blob/master/network.h#L64)

    x.convertTo(y, CV_32F, 1.0/255);

**Comment by twhite2219** [comment]
so in response to this, would the prediction/ real time values have to have this same filter applied.... it is the 1.f part i do  not understand

**Comment by twhite2219** [comment]
So i Debugged it and made it print the raw result returned from the NN and all are correct. It turns out it is the MinMaxLoc that is not calculating the highest value properly... is there a better way to calculate the highest value???

**Comment by berak** [comment]
hehe, you're checking min, not max position [here](https://github.com/twhite2219/selfdrivingcarV1/blob/master/network.h#L150)

you need:

     cv::minMaxLoc(Result, 0, 0, 0, &max_loc);

**Comment by twhite2219** [comment]
I realised. fixed now. all working fully. Thanks berak.
